---
apiVersion: "autoscaling.k8s.io/v1beta2"
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "name" . }}-vpa
  namespace: {{ .Release.Namespace }}
spec:
  targetRef:
    apiVersion: {{ include "deploymentversion" . }}
    kind: Deployment
    name: {{ include "name" . }}
  updatePolicy:
    updateMode: "Auto"