required = [
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen"
]

[[override]]
  name = "github.com/gardener/gardener"
  revision = "0.27.0"

[[override]]
  name = "github.com/gardener/machine-controller-manager"
  source = "github.com/kubeforge/machine-controller-manager"
  revision = "6ed76483c551ac8d66e24a363730d03e2dfefee6"

[[override]]
  name = "github.com/gardener/gardener-resource-manager"
  revision = "0.3.0"

[[override]]
  name = "sigs.k8s.io/controller-runtime"
  version = "0.2.0-beta.2"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.14.0"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.14.0"

[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.14.0"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.14.0"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.14.0"

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.14.0"

[[override]]
  name = "k8s.io/component-base"
  version = "kubernetes-1.14.0"

[[override]]
  name = "k8s.io/kube-aggregator"
  version = "kubernetes-1.14.0"

[[override]]
  name = "k8s.io/kubelet"
  version = "kubernetes-1.14.0"

# use the same version that is referenced by k8s.io/apiserver
[[override]]
  name = "github.com/docker/docker"
  revision = "a9fbbdc8dd8794b20af358382ab780559bca589d"

# use the same version that is referenced by k8s.io, mainly required by Helm
# https://github.com/kubernetes/kubernetes/blob/v1.13.5/Godeps/Godeps.json
[[override]]
  name = "github.com/russross/blackfriday"
  revision = "300106c228d52c8941d4b3de6054a6062a86dda3"

[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"

[[override]]
  name = "github.com/jmespath/go-jmespath"
  version = "^0.2.2"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "~1.12.48"

[[constraint]]
  name = "github.com/aliyun/aliyun-oss-go-sdk"
  version = "v2.0.1"

[[constraint]]
  name = "github.com/packethost/packngo"
  revision = "b3b45f1b4979af3ace1cd5450768ab387b40ae5b"

[[constraint]]
  name = "github.com/Azure/azure-storage-blob-go"
  version = "v0.7.0"

[[constraint]]
  name = "github.com/jetstack/cert-manager"
  version = "v0.6.0"

[[constraint]]
  name = "github.com/gophercloud/gophercloud"
  version = "v0.2.0"

[[constraint]]
  name = "github.com/gophercloud/utils"
  revision = "25f1b77b8c0367b43939dbb20f5dd12e3c9b0053"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.2"

[[constraint]]
  name = "github.com/gobuffalo/packr"
  version = "1.21.9"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/Masterminds/semver"
  version = "~1.4.0"

[[constraint]]
  name = "golang.org/x/oauth2"
  revision = "c85d3e98c914e3a33234ad863dcbff5dbc425bb8"

[[constraint]]
  name = "google.golang.org/api"
  version = "0.2.0"

[[constraint]]
name = "cloud.google.com/go"
version = "0.40.0"

[[constraint]]
  name = "github.com/coreos/go-systemd"
  version = "v19"

# Dependencies for testing purposes only

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "~1.3.0"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "~1.4.0"

[[constraint]]
  name = "github.com/golang/mock"
  version = "1.2.0"

[[constraint]]
  name = "github.com/go-logr/logr"
  version = "v0.1.0"

[[constraint]]
  name = "github.com/go-logr/zapr"
  version = "v0.1.0"

[[constraint]]
  name = "go.uber.org/zap"
  version = "v1.9.1"

[prune]
  unused-packages = true
  go-tests = true
  non-go = true

  [[prune.project]]
    name = "k8s.io/code-generator"
    unused-packages = false
    non-go = false

  [[prune.project]]
    name = "github.com/golang/mock"
    unused-packages = false
