kubernetesVersion: 0.0.1
#[Global]
authUrl: fooURL
domainName: fooDomain
tenantName: fooTenant
username: barUser
password: barPass
# [LoadBalancer]
lbProvider: foobar
floatingNetworkID: foo-bar-123
subnetID: foo-bar-123
# [Metadata]
dhcpDomain: foobar
requestTimeout: 2s