apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-provider-config
  namespace: {{ .Release.Namespace }}
data:
  cloudprovider.conf: |
    [Global]
    auth-url: {{ .Values.authUrl }}
    domain-name: {{ .Values.domainName }}
    tenant-name: {{ .Values.tenantName }}
    username: {{ .Values.username }}
    password: {{ .Values.password }}
    [LoadBalancer]
    lb-version=v2
    lb-provider: {{ .Values.lbProvider }}
    floating-network-id: {{ .Values.floatingNetworkID }}
    subnet-id: {{ .Values.subnetID }}
    create-monitor=true
    monitor-delay=60s
    monitor-timeout=30s
    monitor-max-retries=5
    {{- if and (semverCompare ">= 1.10.1" .Values.kubernetesVersion) (semverCompare "< 1.10.3" .Values.kubernetesVersion) }}
    [Metadata]
      {{- if (ne .Values.dhcpDomain "") }}
        dhcp-domain=.Values.dhcp-domain
      {{- end }}
      {{- if (ne .Values.requestTimeout "") }}
        request-timeout=.Values.request-timeout
      {{- end }}
    {{- end }}