// +build !ignore_autogenerated

/*
Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	kubevirt "github.com/gardener/gardener-extensions/controllers/provider-kubevirt/pkg/apis/kubevirt"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*CloudControllerManagerConfig)(nil), (*kubevirt.CloudControllerManagerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CloudControllerManagerConfig_To_kubevirt_CloudControllerManagerConfig(a.(*CloudControllerManagerConfig), b.(*kubevirt.CloudControllerManagerConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kubevirt.CloudControllerManagerConfig)(nil), (*CloudControllerManagerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kubevirt_CloudControllerManagerConfig_To_v1alpha1_CloudControllerManagerConfig(a.(*kubevirt.CloudControllerManagerConfig), b.(*CloudControllerManagerConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ControlPlaneConfig)(nil), (*kubevirt.ControlPlaneConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ControlPlaneConfig_To_kubevirt_ControlPlaneConfig(a.(*ControlPlaneConfig), b.(*kubevirt.ControlPlaneConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kubevirt.ControlPlaneConfig)(nil), (*ControlPlaneConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kubevirt_ControlPlaneConfig_To_v1alpha1_ControlPlaneConfig(a.(*kubevirt.ControlPlaneConfig), b.(*ControlPlaneConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InfrastructureConfig)(nil), (*kubevirt.InfrastructureConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_InfrastructureConfig_To_kubevirt_InfrastructureConfig(a.(*InfrastructureConfig), b.(*kubevirt.InfrastructureConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kubevirt.InfrastructureConfig)(nil), (*InfrastructureConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kubevirt_InfrastructureConfig_To_v1alpha1_InfrastructureConfig(a.(*kubevirt.InfrastructureConfig), b.(*InfrastructureConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InfrastructureStatus)(nil), (*kubevirt.InfrastructureStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_InfrastructureStatus_To_kubevirt_InfrastructureStatus(a.(*InfrastructureStatus), b.(*kubevirt.InfrastructureStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kubevirt.InfrastructureStatus)(nil), (*InfrastructureStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kubevirt_InfrastructureStatus_To_v1alpha1_InfrastructureStatus(a.(*kubevirt.InfrastructureStatus), b.(*InfrastructureStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NodeStatus)(nil), (*kubevirt.NodeStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NodeStatus_To_kubevirt_NodeStatus(a.(*NodeStatus), b.(*kubevirt.NodeStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kubevirt.NodeStatus)(nil), (*NodeStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kubevirt_NodeStatus_To_v1alpha1_NodeStatus(a.(*kubevirt.NodeStatus), b.(*NodeStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_CloudControllerManagerConfig_To_kubevirt_CloudControllerManagerConfig(in *CloudControllerManagerConfig, out *kubevirt.CloudControllerManagerConfig, s conversion.Scope) error {
	out.KubernetesConfig = in.KubernetesConfig
	return nil
}

// Convert_v1alpha1_CloudControllerManagerConfig_To_kubevirt_CloudControllerManagerConfig is an autogenerated conversion function.
func Convert_v1alpha1_CloudControllerManagerConfig_To_kubevirt_CloudControllerManagerConfig(in *CloudControllerManagerConfig, out *kubevirt.CloudControllerManagerConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_CloudControllerManagerConfig_To_kubevirt_CloudControllerManagerConfig(in, out, s)
}

func autoConvert_kubevirt_CloudControllerManagerConfig_To_v1alpha1_CloudControllerManagerConfig(in *kubevirt.CloudControllerManagerConfig, out *CloudControllerManagerConfig, s conversion.Scope) error {
	out.KubernetesConfig = in.KubernetesConfig
	return nil
}

// Convert_kubevirt_CloudControllerManagerConfig_To_v1alpha1_CloudControllerManagerConfig is an autogenerated conversion function.
func Convert_kubevirt_CloudControllerManagerConfig_To_v1alpha1_CloudControllerManagerConfig(in *kubevirt.CloudControllerManagerConfig, out *CloudControllerManagerConfig, s conversion.Scope) error {
	return autoConvert_kubevirt_CloudControllerManagerConfig_To_v1alpha1_CloudControllerManagerConfig(in, out, s)
}

func autoConvert_v1alpha1_ControlPlaneConfig_To_kubevirt_ControlPlaneConfig(in *ControlPlaneConfig, out *kubevirt.ControlPlaneConfig, s conversion.Scope) error {
	out.LoadBalancerProvider = in.LoadBalancerProvider
	out.CloudControllerManager = (*kubevirt.CloudControllerManagerConfig)(unsafe.Pointer(in.CloudControllerManager))
	return nil
}

// Convert_v1alpha1_ControlPlaneConfig_To_kubevirt_ControlPlaneConfig is an autogenerated conversion function.
func Convert_v1alpha1_ControlPlaneConfig_To_kubevirt_ControlPlaneConfig(in *ControlPlaneConfig, out *kubevirt.ControlPlaneConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_ControlPlaneConfig_To_kubevirt_ControlPlaneConfig(in, out, s)
}

func autoConvert_kubevirt_ControlPlaneConfig_To_v1alpha1_ControlPlaneConfig(in *kubevirt.ControlPlaneConfig, out *ControlPlaneConfig, s conversion.Scope) error {
	out.LoadBalancerProvider = in.LoadBalancerProvider
	out.CloudControllerManager = (*CloudControllerManagerConfig)(unsafe.Pointer(in.CloudControllerManager))
	return nil
}

// Convert_kubevirt_ControlPlaneConfig_To_v1alpha1_ControlPlaneConfig is an autogenerated conversion function.
func Convert_kubevirt_ControlPlaneConfig_To_v1alpha1_ControlPlaneConfig(in *kubevirt.ControlPlaneConfig, out *ControlPlaneConfig, s conversion.Scope) error {
	return autoConvert_kubevirt_ControlPlaneConfig_To_v1alpha1_ControlPlaneConfig(in, out, s)
}

func autoConvert_v1alpha1_InfrastructureConfig_To_kubevirt_InfrastructureConfig(in *InfrastructureConfig, out *kubevirt.InfrastructureConfig, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_InfrastructureConfig_To_kubevirt_InfrastructureConfig is an autogenerated conversion function.
func Convert_v1alpha1_InfrastructureConfig_To_kubevirt_InfrastructureConfig(in *InfrastructureConfig, out *kubevirt.InfrastructureConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_InfrastructureConfig_To_kubevirt_InfrastructureConfig(in, out, s)
}

func autoConvert_kubevirt_InfrastructureConfig_To_v1alpha1_InfrastructureConfig(in *kubevirt.InfrastructureConfig, out *InfrastructureConfig, s conversion.Scope) error {
	return nil
}

// Convert_kubevirt_InfrastructureConfig_To_v1alpha1_InfrastructureConfig is an autogenerated conversion function.
func Convert_kubevirt_InfrastructureConfig_To_v1alpha1_InfrastructureConfig(in *kubevirt.InfrastructureConfig, out *InfrastructureConfig, s conversion.Scope) error {
	return autoConvert_kubevirt_InfrastructureConfig_To_v1alpha1_InfrastructureConfig(in, out, s)
}

func autoConvert_v1alpha1_InfrastructureStatus_To_kubevirt_InfrastructureStatus(in *InfrastructureStatus, out *kubevirt.InfrastructureStatus, s conversion.Scope) error {
	if err := Convert_v1alpha1_NodeStatus_To_kubevirt_NodeStatus(&in.Node, &out.Node, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_InfrastructureStatus_To_kubevirt_InfrastructureStatus is an autogenerated conversion function.
func Convert_v1alpha1_InfrastructureStatus_To_kubevirt_InfrastructureStatus(in *InfrastructureStatus, out *kubevirt.InfrastructureStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_InfrastructureStatus_To_kubevirt_InfrastructureStatus(in, out, s)
}

func autoConvert_kubevirt_InfrastructureStatus_To_v1alpha1_InfrastructureStatus(in *kubevirt.InfrastructureStatus, out *InfrastructureStatus, s conversion.Scope) error {
	if err := Convert_kubevirt_NodeStatus_To_v1alpha1_NodeStatus(&in.Node, &out.Node, s); err != nil {
		return err
	}
	return nil
}

// Convert_kubevirt_InfrastructureStatus_To_v1alpha1_InfrastructureStatus is an autogenerated conversion function.
func Convert_kubevirt_InfrastructureStatus_To_v1alpha1_InfrastructureStatus(in *kubevirt.InfrastructureStatus, out *InfrastructureStatus, s conversion.Scope) error {
	return autoConvert_kubevirt_InfrastructureStatus_To_v1alpha1_InfrastructureStatus(in, out, s)
}

func autoConvert_v1alpha1_NodeStatus_To_kubevirt_NodeStatus(in *NodeStatus, out *kubevirt.NodeStatus, s conversion.Scope) error {
	out.KeyName = in.KeyName
	return nil
}

// Convert_v1alpha1_NodeStatus_To_kubevirt_NodeStatus is an autogenerated conversion function.
func Convert_v1alpha1_NodeStatus_To_kubevirt_NodeStatus(in *NodeStatus, out *kubevirt.NodeStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_NodeStatus_To_kubevirt_NodeStatus(in, out, s)
}

func autoConvert_kubevirt_NodeStatus_To_v1alpha1_NodeStatus(in *kubevirt.NodeStatus, out *NodeStatus, s conversion.Scope) error {
	out.KeyName = in.KeyName
	return nil
}

// Convert_kubevirt_NodeStatus_To_v1alpha1_NodeStatus is an autogenerated conversion function.
func Convert_kubevirt_NodeStatus_To_v1alpha1_NodeStatus(in *kubevirt.NodeStatus, out *NodeStatus, s conversion.Scope) error {
	return autoConvert_kubevirt_NodeStatus_To_v1alpha1_NodeStatus(in, out, s)
}
