replicas: 1
kubernetesVersion: 1.7.5
clusterName: shoot-foo-bar
podNetwork: 192.168.0.0/16
podAnnotations: {}
featureGates: {}
  # CustomResourceValidation: true
  # RotateKubeletServerCertificate: false
images:
  hyperkube: image-repository:image-tag
resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 512Mi